x-common: &common
  restart: "no"
  env_file:
    - .env


services:

  apache:
    <<: *common
    image: httpd:2.4-alpine
    hostname: symfony.test
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - php_run:/run/php
      - .:/application:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./certs/apache:/data/certs

  app:
    <<: *common
    image: fixeditforyou/php8.3-fpm:dev
    working_dir: /application
    tmpfs:
      - /run:mode=777
      - /tmp:mode=777
      - /symfony/cache:mode=777
    volumes:
      - php_run:/run/php
      - .:/application:z
      - "$HOME/.config/composer/:/tmp/composer"
      - "$HOME/.cache/composer/:/tmp/composer/cache"


volumes:
  php_run:
    driver: local
    driver_opts:
      type:   "tmpfs"
      o:      "mode=1777"
      device: "tmpfs"
